/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "ap-south-1:2368d534-1d43-4d97-8b6c-c47db8130de4",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_rtq4IS3G6",
    "aws_user_pools_web_client_id": "5n7ajudlga1gmip5jqais1mq23",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "placify7a49080229e747fe93064a1529f4372e497d0-dev",
    "aws_user_files_s3_bucket_region": "ap-south-1"
};


export default awsmobile;
