/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "ap-south-1:46b50679-cfeb-4277-a5cb-ac11886f0c56",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_edjQIi2Dy",
    "aws_user_pools_web_client_id": "64g5ss4vo4cev3lc70h6q92eva",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "placify835618d201a642e5b582d368e5c08f29382d8-dev",
    "aws_user_files_s3_bucket_region": "ap-south-1"
};


export default awsmobile;
